In [7]:
import torch
import numpy as np

In [8]:
np.random.seed(1)
a = np.random.random(size=12)
a = a.reshape((1,3,2,2))
a

array([[[[4.17022005e-01, 7.20324493e-01],
         [1.14374817e-04, 3.02332573e-01]],

        [[1.46755891e-01, 9.23385948e-02],
         [1.86260211e-01, 3.45560727e-01]],

        [[3.96767474e-01, 5.38816734e-01],
         [4.19194514e-01, 6.85219500e-01]]]])

In [15]:
w = torch.tensor(a)

In [17]:
ws=[]
for c in range(10):
    w = torch.tensor(a)
    w = torch.mean(w, dim=-1)
    w = w.flatten(start_dim=1)
#     w = w.unsqueeze(-1)
    ws.append(w)
res = torch.stack(ws, dim=-1)

In [19]:
res.size()

torch.Size([1, 6, 10])

In [2]:
np.random.seed(1)
a = np.random.random(size=10)
a = a / np.sum(a)

In [3]:
np.random.seed(1)
b = np.random.random(size=(20,10))

In [4]:
y_pred = torch.tensor(a).unsqueeze(0)
W = torch.tensor(b).unsqueeze(0)*5

In [5]:
scale=1.0
EPS = 1e-12

In [6]:
A = torch.diag_embed(y_pred)  # (B, cl, cl)
p = torch.unsqueeze(y_pred, 2) # (B, cl, 1)
A = A - torch.matmul(p, torch.transpose(p, 1, 2)) # A-pp^T
A = A + torch.eye(int(A.size()[1]), int(A.size()[2])).unsqueeze(0) * EPS
e, U = torch.linalg.eigh(A)
e = torch.clamp(e, min=1e-20, max=np.inf)
Sigma = torch.diag_embed(torch.sqrt(e))
L = torch.matmul(U, Sigma)
B = torch.matmul(W, L)  # (B, K, C) x (B, C, C) --> (B, K, C)
B_T = torch.transpose(B, 1, 2) # (B, C, K)
C = torch.matmul(B_T, B) # (B, C, C)
C = C + torch.eye(int(C.size()[1]), int(C.size()[2])).unsqueeze(0) * EPS
H_e, _ = torch.linalg.eigh(C)
avg_beta = torch.mean(H_e[:, -1]) # Eigenvalues. Shape is [..., N]. Sorted in non-decreasing order.
print(avg_beta * scale)

tensor(12.4697, dtype=torch.float64)


In [9]:
e

tensor([[2.0780e-01, 1.5660e-01, 1.2940e-01, 1.1581e-01, 1.0042e-01, 6.5493e-02,
         4.9813e-02, 3.1578e-02, 9.9999e-13, 4.0389e-05]], dtype=torch.float64)

In [10]:
U

tensor([[[-1.4532e-01+0.j,  3.8716e-01+0.j,  7.3267e-01+0.j,  3.2648e-01+0.j,
          -1.5802e-01+0.j,  1.7745e-01+0.j,  9.6590e-02+0.j, -9.3292e-02+0.j,
           3.1623e-01+0.j, -1.0539e-01+0.j],
         [ 8.9315e-01+0.j, -2.2232e-01+0.j,  4.0001e-02+0.j,  8.3394e-02+0.j,
          -6.8220e-02+0.j,  1.2573e-01+0.j,  7.7054e-02+0.j, -8.2436e-02+0.j,
           3.1623e-01+0.j, -1.0537e-01+0.j],
         [-1.4436e-05+0.j,  1.6313e-05+0.j, -4.8876e-06+0.j, -1.2939e-05+0.j,
           1.3868e-05+0.j, -4.9853e-05+0.j, -4.4030e-05+0.j,  8.1905e-05+0.j,
           3.1623e-01+0.j,  9.4868e-01+0.j],
         [-7.0973e-02+0.j,  1.1158e-01+0.j, -5.0181e-02+0.j, -2.0077e-01+0.j,
           8.4985e-01+0.j,  2.8190e-01+0.j,  1.2518e-01+0.j, -1.0585e-01+0.j,
           3.1623e-01+0.j, -1.0540e-01+0.j],
         [-2.3880e-02+0.j,  2.9803e-02+0.j, -9.8035e-03+0.j, -2.7788e-02+0.j,
           3.3216e-02+0.j, -2.2214e-01+0.j, -8.8752e-01+0.j, -2.2001e-01+0.j,
           3.1623e-01+0.j, -1.0544e-01+0

In [15]:
x = torch.tensor([1,2,3,4], dtype=torch.float)

In [16]:
x = x.view((-1, 1))
x

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [17]:
torch.unbind(x)

(tensor([1.]), tensor([2.]), tensor([3.]), tensor([4.]))